### ISSUE TITLE
move-lens runs out of heap

### ISSUE THREAD

**Issue by vext01** [softdevteam/new_benchmarking_experiment#10]
```
[2019-07-10 12:28:11: INFO] stderr: java.lang.OutOfMemoryError: Java heap space
[2019-07-10 12:28:11: INFO] stderr: 19/07/10 12:28:11 ERROR ContextCleaner: Error cleaning broadcast 780723
[2019-07-10 12:28:11: INFO] stderr: org.apache.spark.rpc.RpcTimeoutException: Futures timed out after [120 seconds]. This timeout is controlled by spark.rpc.askTimeout
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout.org$apache$spark$rpc$RpcTimeout$$createRpcTimeoutException(RpcTimeout.scala:48)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:63)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:59)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:83)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.storage.BlockManagerMaster.removeBroadcast(BlockManagerMaster.scala:143)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.broadcast.TorrentBroadcast$.unpersist(TorrentBroadcast.scala:267)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.broadcast.TorrentBroadcastFactory.unbroadcast(TorrentBroadcastFactory.scala:45)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.broadcast.BroadcastManager.unbroadcast(BroadcastManager.scala:60)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner.doCleanupBroadcast(ContextCleaner.scala:232)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:188)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1$$anonfun$apply$mcV$sp$2.apply(ContextCleaner.scala:179)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.Option.foreach(Option.scala:257)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner$$anonfun$org$apache$spark$ContextCleaner$$keepCleaning$1.apply$mcV$sp(ContextCleaner.scala:179)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1229)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner.org$apache$spark$ContextCleaner$$keepCleaning(ContextCleaner.scala:172)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.ContextCleaner$$anon$1.run(ContextCleaner.scala:67)
[2019-07-10 12:28:11: INFO] stderr: Caused by: java.util.concurrent.TimeoutException: Futures timed out after [120 seconds]
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[2019-07-10 12:28:11: INFO] stderr: 	at scala.concurrent.Await$.result(package.scala:190)
[2019-07-10 12:28:11: INFO] stderr: 	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:81)
[2019-07-10 12:28:11: INFO] stderr: 	... 12 more
[2019-07-10 12:28:23: INFO] stderr: 19/07/10 12:28:23 ERROR TaskSetManager: Task 1 in stage 2553648.0 failed 1 times; aborting job
[2019-07-10 12:28:23: INFO] stderr: 19/07/10 12:28:23 ERROR SparkUncaughtExceptionHandler: Uncaught exception in thread Thread[Executor task launch worker-564,5,main]
[2019-07-10 12:28:23: INFO] stderr: java.lang.OutOfMemoryError: Java heap space
```

**Comment by ltratt** [comment]
Closing this in favour of the issue on the main Renaissance repo (https://github.com/renaissance-benchmarks/renaissance/issues/187).
